# app.py

from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import joblib
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder
import sqlite3
import secrets # For generating secure random tokens

# ------------------------------------------------------------------------
# Flask app setup
# ------------------------------------------------------------------------
app = Flask(__name__)
CORS(app, resources={
    r"/*": {
        "origins": ["http://localhost:*"],
        "methods": ["OPTIONS", "POST", "GET", "PUT", "DELETE"],
        "allow_headers": ["Content-Type"]
    }
})

# ------------------------------------------------------------------------
# Constants / Filepaths
# ------------------------------------------------------------------------
CSV_PATH = "dataset.csv"          # Path to the original CSV
MODEL_WEEK_PATH = "xgb_model_week.pkl"     # Saved week‐ahead model
MODEL_MONTH_PATH = "xgb_model_month.pkl"   # Saved month‐ahead model
DB_PATH = "users.db"              # Path to the SQLite database

# ------------------------------------------------------------------------
# Load saved XGBoost models
# ------------------------------------------------------------------------
model_week = joblib.load(MODEL_WEEK_PATH)
model_month = joblib.load(MODEL_MONTH_PATH)

# Global store for access tokens (as requested, not persistent across server restarts)
access_tokens = []

# ------------------------------------------------------------------------
# Utility functions (same as used during training)
# ------------------------------------------------------------------------
def preprocess_data(df: pd.DataFrame):
    """
    1. Convert 'Date' to datetime, sort by ['Product ID', 'Date'].
    2. Extract date components: Year, Month, Day, DayOfWeek, Quarter, WeekOfYear.
    3. For each 'Product ID', create lag features of 'Sales' at lags [1,7,14,30].
    4. Compute rolling mean/std of 'Sales' over windows [7,14,30] days per product.
    5. Derive price‐related features:
         - Price_vs_Competitor = Price / Competitor Pricing
         - Discount_Price_Ratio = Discount / Price
         - Effective_Price = Price * (1 - Discount / 100)
    6. Label‐encode categorical columns: 'Product ID', 'Category', 'Region',
       'Weather Condition', 'Seasonality'.
    Returns:
      - processed_df: DataFrame with new features (NaN rows from lags/rolls dropped).
      - encoders: dict mapping column name → fitted LabelEncoder.
    """
    df_proc = df.copy()
    # 1. Convert and sort
    df_proc["Date"] = pd.to_datetime(df_proc["Date"])
    df_proc = df_proc.sort_values(["Product ID", "Date"]).reset_index(drop=True)
    
    # 2. Date components
    df_proc["Year"] = df_proc["Date"].dt.year
    df_proc["Month"] = df_proc["Date"].dt.month
    df_proc["Day"] = df_proc["Date"].dt.day
    df_proc["DayOfWeek"] = df_proc["Date"].dt.dayofweek      # Monday=0 … Sunday=6
    df_proc["Quarter"] = df_proc["Date"].dt.quarter
    df_proc["WeekOfYear"] = df_proc["Date"].dt.isocalendar().week
    
    # 3. Lag features per product
    lag_days = [1, 7, 14, 30]
    for lag in lag_days:
        df_proc[f"Sales_lag_{lag}"] = df_proc.groupby("Product ID")["Sales"].shift(lag)
    
    # 4. Rolling mean & std per product for windows [7,14,30]
    roll_windows = [7, 14, 30]
    for window in roll_windows:
        df_proc[f"Sales_roll_mean_{window}"] = (
            df_proc.groupby("Product ID")["Sales"]
                   .rolling(window, min_periods=1)
                   .mean()
                   .shift(1)
                   .reset_index(level=0, drop=True)
        )
        df_proc[f"Sales_roll_std_{window}"] = (
            df_proc.groupby("Product ID")["Sales"]
                   .rolling(window, min_periods=1)
                   .std()
                   .shift(1)
                   .reset_index(level=0, drop=True)
        )
    
    # 5. Price-related features
    df_proc["Price_vs_Competitor"] = df_proc["Price"] / (df_proc["Competitor Pricing"] + 1e-6)
    df_proc["Discount_Price_Ratio"] = df_proc["Discount"] / (df_proc["Price"] + 1e-6)
    df_proc["Effective_Price"] = df_proc["Price"] * (1 - df_proc["Discount"] / 100)
    
    # 6. Label-encode categorical columns
    categorical_cols = ["Product ID", "Category", "Region", "Weather Condition", "Seasonality"]
    encoders = {}
    for col in categorical_cols:
        le = LabelEncoder()
        df_proc[f"{col}_encoded"] = le.fit_transform(df_proc[col].astype(str))
        encoders[col] = le
    
    # Drop any rows with NaNs generated by lags/rolling
    df_proc = df_proc.dropna().reset_index(drop=True)
    
    return df_proc, encoders

def create_forecasting_features(data: pd.DataFrame, target_days: int):
    """
    Shifts 'Sales' by -target_days within each 'Product ID' group to create the target variable.
    Returns a new DataFrame with a column 'Sales_target_{target_days}d'.
    """
    df_f = data.copy().sort_values(["Product ID", "Date"]).reset_index(drop=True)
    df_f[f"Sales_target_{target_days}d"] = (
        df_f.groupby("Product ID")["Sales"].shift(-target_days)
    )
    # Drop rows where target is NaN (last target_days per product)
    df_f = df_f.dropna(subset=[f"Sales_target_{target_days}d"]).reset_index(drop=True)
    return df_f

def prepare_model_data(data: pd.DataFrame, target_days: int):
    """
    1. Calls create_forecasting_features to get target column.
    2. Defines feature columns (the same as during training).
    3. Drops rows with any NaNs in those feature columns or the target.
    Returns:
      - X: DataFrame of features
      - y: Series of target (Sales_target_{target_days}d)
      - dates: Series of Date (for mapping predictions to dates)
      - feature_cols: list of feature names
    """
    df_feat = create_forecasting_features(data, target_days)
    
    feature_cols = [
        # Date components
        "Year", "Month", "Day", "DayOfWeek", "Quarter", "WeekOfYear",
        # Business features
        "Units Sold", "Price", "Discount", "Holiday/Promotion", "Competitor Pricing",
        # Encoded categoricals
        "Product ID_encoded", "Category_encoded", "Region_encoded",
        "Weather Condition_encoded", "Seasonality_encoded",
        # Lag features
        "Sales_lag_1", "Sales_lag_7", "Sales_lag_14", "Sales_lag_30",
        # Rolling statistics
        "Sales_roll_mean_7", "Sales_roll_std_7",
        "Sales_roll_mean_14", "Sales_roll_std_14",
        "Sales_roll_mean_30", "Sales_roll_std_30",
        # Price-ratio features
        "Price_vs_Competitor", "Discount_Price_Ratio", "Effective_Price"
    ]
    
    df_model = df_feat.dropna(subset=feature_cols + [f"Sales_target_{target_days}d"]).reset_index(drop=True)
    X = df_model[feature_cols].copy()
    y = df_model[f"Sales_target_{target_days}d"].copy()
    dates = df_model["Date"].copy()
    
    return X, y, dates, feature_cols

# ------------------------------------------------------------------------
# Endpoint: Predict on the last N days from CSV
# ------------------------------------------------------------------------
@app.route("/predict_last", methods=["POST"])
def predict_last():
    """
    Expects JSON payload:
      {
        "model": "week" or "month",
        "n_days": <integer>,
        "access_token": <string>
      }
    Reads the CSV, preprocesses it, builds X,y for the chosen target horizon,
    then takes the last n_days rows of X, predicts using the corresponding model,
    and returns a JSON mapping Date → Predicted_Sales for those last n_days.
    """
    # Validate access token
    access_token = request.json.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid access token."}), 401
    if not request.is_json:
        return jsonify({"error": "Request must be JSON."}), 400
    if not request.json:
        return jsonify({"error": "Request must contain JSON data."}), 400
    if "model" not in request.json or "n_days" not in request.json:
        return jsonify({"error": "Request must contain 'model' and 'n_days' fields."}), 400
    
    try:
        payload = request.get_json()
        if not isinstance(payload, dict):
            raise ValueError("Payload must be a JSON object.")
        
        model_type = payload.get("model", "").lower()
        n_days = payload.get("n_days", None)
        
        if model_type not in ("week", "month"):
            raise ValueError("Field 'model' must be 'week' or 'month'.")
        if not isinstance(n_days, int) or n_days <= 0:
            raise ValueError("Field 'n_days' must be a positive integer.")
        
        # 1. Load CSV
        df_raw = pd.read_csv(CSV_PATH)
        
        # 2. Preprocess
        processed_df, _ = preprocess_data(df_raw)
        
        # 3. Prepare data for the chosen horizon
        if model_type == "week":
            target_days = 7
            model = model_week
        else:  # "month"
            target_days = 30
            model = model_month
        
        X_all, y_all, dates_all, feature_cols = prepare_model_data(processed_df, target_days)
        
        total_rows = X_all.shape[0]
        if n_days > total_rows:
            raise ValueError(f"Requested n_days ({n_days}) exceeds available rows ({total_rows}).")
        
        # 4. Select last n_days of X_all
        X_recent = X_all.iloc[-n_days:].reset_index(drop=True)
        dates_recent = dates_all.iloc[-n_days:].dt.strftime("%Y-%m-%d").tolist()
        
        # 5. Predict
        preds = model.predict(X_recent)
        
        # 6. Build response mapping each date to its predicted sales
        result = [
            {"Date": dates_recent[i], "Predicted_Sales": float(preds[i])}
            for i in range(n_days)
        ]
        
        return jsonify({"predictions": result}), 200
    
    except Exception as e:
        return jsonify({"error": str(e)}), 400


# ------------------------------------------------------------------------
# Endpoint: Login
# ------------------------------------------------------------------------
@app.route("/login", methods=["POST"])
def login():
    """
    Expects JSON payload:
      {
        "email": "<user_email>",
        "pass": "<user_password>"
      }
    Checks credentials against the SQLite database.
    If correct, generates a 16-character access token, stores it globally,
    and returns it. Otherwise, returns an error.
    """
    try:
        payload = request.get_json()
        if not isinstance(payload, dict):
            return jsonify({"error": "Payload must be a JSON object."}), 400

        email = payload.get("email")
        password = payload.get("pass") # Using "pass" as per request

        if not email or not password:
            return jsonify({"error": "Email and password are required."}), 400

        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        # IMPORTANT: In a real app, passwords must be hashed and compared securely.
        # This example uses plaintext for simplicity as per the request's implication.
        cursor.execute("SELECT password FROM users WHERE email = ?", (email,))
        user_record = cursor.fetchone()
        conn.close()

        if user_record and user_record[0] == password:
            token = secrets.token_hex(8)  # Generates a 16-character hex token
            access_tokens.append(token)
            app.logger.info(f"Login successful for {email}, token generated.")
            return jsonify({"access_token": token}), 200
        else:
            app.logger.warning(f"Failed login attempt for {email}.")
            return jsonify({"error": "Invalid email or password."}), 401

    except Exception as e:
        app.logger.error(f"Login endpoint error: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500


# ------------------------------------------------------------------------
# Access Token Validation
# ------------------------------------------------------------------------
def is_valid_access_token(token: str) -> bool:
    """
    Checks if the provided access token is in the global access_tokens list.
    Args:
        token: The access token string to validate.
    Returns:
        True if the token is valid, False otherwise.
    """
    return token in access_tokens


# ------------------------------------------------------------------------
# Endpoint: Logout
# ------------------------------------------------------------------------
@app.route("/logout", methods=["POST"])
def logout():
    """
    Expects JSON payload:
      {
        "access_token": "<user_access_token>"
      }
    Removes the access token from the global list.
    """
    try:
        payload = request.get_json()
        if not isinstance(payload, dict):
            return jsonify({"error": "Payload must be a JSON object."}), 400

        token_to_remove = payload.get("access_token")

        if not token_to_remove:
            return jsonify({"error": "Access token is required."}), 400

        if token_to_remove in access_tokens:
            access_tokens.remove(token_to_remove)
            app.logger.info(f"Token {token_to_remove} successfully removed (logged out).")
            return jsonify({"message": "Logout successful."}), 200
        else:
            app.logger.warning(f"Attempted to logout with non-existent token: {token_to_remove}.")
            return jsonify({"error": "Invalid or expired access token."}), 400
    except Exception as e:
        app.logger.error(f"Logout endpoint error: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500


# ------------------------------------------------------------------------
# Endpoint: Get Sales Statistics
# ------------------------------------------------------------------------
@app.route("/getstats", methods=["POST"])
def get_stats():
    """
    Expects JSON payload:
      {
        "range": "This Day" | "Last 7 Days" | "Last 30 Days",
        "access_token": "<user_access_token>"
      }
    Retrieves sum of 'Units Sold' and 'Sales' for the specified period
    from the dataset.csv file.
    """
    try:
        # Validate access token
        access_token = request.json.get("access_token")
        if not is_valid_access_token(access_token):
            return jsonify({"error": "Invalid access token."}), 401

        if not request.is_json:
            return jsonify({"error": "Request must be JSON."}), 400
        
        payload = request.get_json()
        if not isinstance(payload, dict):
             return jsonify({"error": "Payload must be a JSON object."}), 400

        range_str = payload.get("range")

        if not range_str:
            return jsonify({"error": "'range' is required."}), 400

        if range_str == "This Day":
            x_days = 1
        elif range_str == "Last 7 Days":
            x_days = 7
        elif range_str == "Last 30 Days":
            x_days = 30
        else:
            return jsonify({"error": "Invalid range. Must be 'This Day', 'Last 7 Days', or 'Last 30 Days'."}), 400

        df = pd.read_csv(CSV_PATH)
        df["Date"] = pd.to_datetime(df["Date"])
        
        if df.empty:
            return jsonify({"rupees": 0, "qty": 0, "message": "Dataset is empty."}), 200

        max_date = df["Date"].max()
        start_date = max_date - pd.Timedelta(days=x_days - 1)
        
        filtered_df = df[(df["Date"] >= start_date) & (df["Date"] <= max_date)]

        total_sales_rupees = filtered_df["Sales"].sum()
        total_units_qty = filtered_df["Units Sold"].sum()

        return jsonify({"rupees": float(total_sales_rupees), "qty": int(total_units_qty)}), 200

    except Exception as e:
        app.logger.error(f"Getstats endpoint error: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500



# ------------------------------------------------------------------------
# Product CRUD Endpoints
# ------------------------------------------------------------------------
@app.route("/products", methods=["POST"])
def create_product():
    """
    Creates a new product.
    Expects JSON payload:
      {
        "ProductID": "<product_id>",
        "Price": <float>,
        "Discount": <float>,
        "QtyRemaining": <integer>,
        "access_token": "<user_access_token>"
      }
    """
    if not request.is_json:
        return jsonify({"error": "Request must be JSON."}), 400
    
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request must contain JSON data."}), 400

    access_token = data.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid access token."}), 401

    product_id = data.get("ProductID")
    price = data.get("Price")
    discount = data.get("Discount")
    qty_remaining = data.get("QtyRemaining")

    if not all([product_id, isinstance(product_id, str),
                price is not None, isinstance(price, (int, float)),
                discount is not None, isinstance(discount, (int, float)),
                qty_remaining is not None, isinstance(qty_remaining, int)]):
        return jsonify({"error": "Missing or invalid type for required fields: ProductID (string), Price (number), Discount (number), QtyRemaining (integer)."}), 400

    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO products (ProductID, Price, Discount, QtyRemaining) VALUES (?, ?, ?, ?)",
            (product_id, float(price), float(discount), int(qty_remaining))
        )
        conn.commit()
        app.logger.info(f"Product {product_id} created successfully.")
        return jsonify({"message": "Product created successfully.", "ProductID": product_id}), 201
    except sqlite3.IntegrityError:
        app.logger.error(f"Error creating product {product_id}: ProductID already exists.")
        return jsonify({"error": f"Product with ProductID '{product_id}' already exists."}), 409
    except sqlite3.Error as e:
        app.logger.error(f"Database error creating product: {str(e)}")
        return jsonify({"error": f"Database error: {str(e)}"}), 500
    except Exception as e:
        app.logger.error(f"Error creating product: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500
    finally:
        if conn:
            conn.close()

@app.route("/products", methods=["GET"])
def get_all_products():
    """
    Retrieves all products.
    Expects access_token as a query parameter: /products?access_token=<token>
    """
    access_token = request.args.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid or missing access token."}), 401

    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row # To get results as dict-like objects
        cursor = conn.cursor()
        cursor.execute("SELECT ProductID, Price, Discount, QtyRemaining FROM products")
        products = [dict(row) for row in cursor.fetchall()]
        app.logger.info("Retrieved all products.")
        return jsonify(products), 200
    except sqlite3.Error as e:
        app.logger.error(f"Database error retrieving all products: {str(e)}")
        return jsonify({"error": f"Database error: {str(e)}"}), 500
    except Exception as e:
        app.logger.error(f"Error retrieving all products: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500
    finally:
        if conn:
            conn.close()

@app.route("/products/<string:product_id>", methods=["GET"])
def get_product(product_id):
    """
    Retrieves a specific product by ProductID.
    Expects access_token as a query parameter: /products/<product_id>?access_token=<token>
    """
    access_token = request.args.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid or missing access token."}), 401

    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute("SELECT ProductID, Price, Discount, QtyRemaining FROM products WHERE ProductID = ?", (product_id,))
        product = cursor.fetchone()
        
        if product:
            app.logger.info(f"Retrieved product {product_id}.")
            return jsonify(dict(product)), 200
        else:
            app.logger.info(f"Product {product_id} not found for retrieval.")
            return jsonify({"error": "Product not found."}), 404
    except sqlite3.Error as e:
        app.logger.error(f"Database error retrieving product {product_id}: {str(e)}")
        return jsonify({"error": f"Database error: {str(e)}"}), 500
    except Exception as e:
        app.logger.error(f"Error retrieving product {product_id}: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500
    finally:
        if conn:
            conn.close()

@app.route("/products/<string:product_id>", methods=["PUT"])
def update_product(product_id):
    """
    Updates an existing product.
    Expects JSON payload with fields to update and access_token:
      {
        "Price": <float>,      // Optional
        "Discount": <float>,   // Optional
        "QtyRemaining": <int>, // Optional
        "access_token": "<user_access_token>"
      }
    """
    if not request.is_json:
        return jsonify({"error": "Request must be JSON."}), 400
    
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request must contain JSON data."}), 400

    access_token = data.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid access token."}), 401

    fields_to_update = {}
    if "Price" in data:
        if not isinstance(data["Price"], (int, float)): return jsonify({"error": "Price must be a number."}), 400
        fields_to_update["Price"] = float(data["Price"])
    if "Discount" in data:
        if not isinstance(data["Discount"], (int, float)): return jsonify({"error": "Discount must be a number."}), 400
        fields_to_update["Discount"] = float(data["Discount"])
    if "QtyRemaining" in data:
        if not isinstance(data["QtyRemaining"], int): return jsonify({"error": "QtyRemaining must be an integer."}), 400
        fields_to_update["QtyRemaining"] = int(data["QtyRemaining"])

    if not fields_to_update:
        return jsonify({"error": "No valid fields provided to update (Price, Discount, QtyRemaining)."}), 400

    set_clause = ", ".join([f"{key} = ?" for key in fields_to_update.keys()])
    values = list(fields_to_update.values())
    values.append(product_id)

    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute(f"UPDATE products SET {set_clause} WHERE ProductID = ?", tuple(values))
        
        if cursor.rowcount == 0:
            app.logger.warning(f"Attempted to update product {product_id}, but it was not found or no changes were applicable.")
            return jsonify({"error": "Product not found or no changes made."}), 404
        
        conn.commit()
        app.logger.info(f"Product {product_id} updated successfully.")
        return jsonify({"message": f"Product {product_id} updated successfully."}), 200
    except sqlite3.Error as e:
        app.logger.error(f"Database error updating product {product_id}: {str(e)}")
        return jsonify({"error": f"Database error: {str(e)}"}), 500
    except Exception as e:
        app.logger.error(f"Error updating product {product_id}: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500
    finally:
        if conn:
            conn.close()

@app.route("/products/<string:product_id>", methods=["DELETE"])
def delete_product(product_id):
    """
    Deletes a specific product by ProductID.
    Expects access_token as a query parameter: /products/<product_id>?access_token=<token>
    """
    access_token = request.args.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid or missing access token."}), 401

    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("DELETE FROM products WHERE ProductID = ?", (product_id,))
        
        if cursor.rowcount == 0:
            app.logger.warning(f"Attempted to delete product {product_id}, but it was not found.")
            return jsonify({"error": "Product not found."}), 404
            
        conn.commit()
        app.logger.info(f"Product {product_id} deleted successfully.")
        return jsonify({"message": f"Product {product_id} deleted successfully."}), 200
    except sqlite3.Error as e:
        app.logger.error(f"Database error deleting product {product_id}: {str(e)}")
        return jsonify({"error": f"Database error: {str(e)}"}), 500
    except Exception as e:
        app.logger.error(f"Error deleting product {product_id}: {str(e)}")
        return jsonify({"error": "An internal server error occurred."}), 500
    finally:
        if conn:
            conn.close()



# ------------------------------------------------------------------------
# Endpoint: Add entry to dataset.csv
# ------------------------------------------------------------------------
@app.route("/add_entry", methods=["POST"])
def add_entry():
    """
    Adds a new entry to the dataset.csv file.
    Expects JSON payload with all required columns for the CSV and an access_token:
      {
        "Date": "YYYY-MM-DD",
        "Product ID": "string",
        "Category": "string",
        "Region": "string",
        "Units Sold": "integer",
        "Price": "float",
        "Discount": "float",
        "Weather Condition": "string",
        "Holiday/Promotion": "integer (0 or 1)",
        "Competitor Pricing": "float",
        "Seasonality": "string",
        "Sales": "float",
        "access_token": "<user_access_token>"
      }
    """
    if not request.is_json:
        return jsonify({"error": "Request must be JSON."}), 400
    
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request must contain JSON data."}), 400

    access_token = data.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid access token."}), 401

    required_fields = [
        "Date", "Product ID", "Category", "Region", "Units Sold", "Price",
        "Discount", "Weather Condition", "Holiday/Promotion",
        "Competitor Pricing", "Seasonality", "Sales"
    ]

    # Check for missing fields
    missing_fields = [field for field in required_fields if field not in data]
    if missing_fields:
        return jsonify({"error": f"Missing required fields: {', '.join(missing_fields)}"}), 400

    # Basic type validation (can be more extensive)
    try:
        new_entry_data = {field: [data[field]] for field in required_fields}
        # Attempt to cast to expected types to catch obvious errors
        new_entry_data["Units Sold"] = [int(data["Units Sold"])]
        new_entry_data["Price"] = [float(data["Price"])]
        new_entry_data["Discount"] = [float(data["Discount"])]
        new_entry_data["Holiday/Promotion"] = [int(data["Holiday/Promotion"])]
        new_entry_data["Competitor Pricing"] = [float(data["Competitor Pricing"])]
        new_entry_data["Sales"] = [float(data["Sales"])]
    except (ValueError, TypeError) as e:
        return jsonify({"error": f"Invalid data type for one or more fields: {str(e)}"}), 400

    try:
        new_entry_df = pd.DataFrame(new_entry_data)
        
        # Append to CSV without header and index
        # The CSV already has an unnamed index column, so we don't want pandas to add another.
        # We also don't want to repeat headers.
        new_entry_df.to_csv(CSV_PATH, mode='a', header=False, index=False)
        
        app.logger.info(f"New entry added to {CSV_PATH} for Product ID {data.get('Product ID')}.")
        return jsonify({"message": "Entry added successfully to dataset.csv"}), 201
    except Exception as e:
        app.logger.error(f"Error adding entry to CSV: {str(e)}")
        return jsonify({"error": f"Failed to add entry to CSV: {str(e)}"}), 500



# ------------------------------------------------------------------------
# Endpoint: Download dataset.csv
# ------------------------------------------------------------------------
@app.route("/download_dataset", methods=["GET"])
def download_dataset():
    """
    Allows authenticated users to download the dataset.csv file.
    Expects access_token as a query parameter: /download_dataset?access_token=<token>
    """
    access_token = request.args.get("access_token")
    if not is_valid_access_token(access_token):
        return jsonify({"error": "Invalid or missing access token."}), 401

    try:
        app.logger.info(f"Dataset download request received with valid token.")
        return send_file(
            CSV_PATH,
            mimetype='text/csv',
            as_attachment=True,
            download_name='records.csv' # This is the name the browser will suggest for the download
        )
    except FileNotFoundError:
        app.logger.error(f"Error downloading dataset: {CSV_PATH} not found.")
        return jsonify({"error": "Dataset file not found on server."}), 404
    except Exception as e:
        app.logger.error(f"Error during dataset download: {str(e)}")
        return jsonify({"error": "An internal server error occurred during file download."}), 500

# ------------------------------------------------------------------------
# Run the Flask app
# ------------------------------------------------------------------------
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
